import type { ProductAvailability, ProductCategory, ProductOptionType } from '@prisma/client'

// Catálogo de demostración. Las fotos viven en `apps/web/public/catalog/` (ver CREDITS.md ahí).
// El orden del arreglo es el orden en que aparecen en el catálogo (el primero se muestra primero).

type Choice = { label: string; value: string }

export type SeedOption = {
  type: ProductOptionType
  label: string
  required?: boolean
  choices?: Choice[]
}

export type SeedProduct = {
  id: string
  name: string
  description: string
  category: ProductCategory
  price: number
  images: string[]
  tags: string[]
  specs: string[]
  personalization: string
  minOrder: string
  leadTime: string
  availability: ProductAvailability
  badge: string | null
  sampleEligible: boolean
  options: SeedOption[]
}

const img = (id: string, count: number) =>
  Array.from({ length: count }, (_, i) => `/catalog/${id}-${i + 1}.jpg`)

const c = {
  negro: { label: 'Negro', value: '#1a1a1a' },
  blanco: { label: 'Blanco', value: '#f7f7f4' },
  crudo: { label: 'Crudo', value: '#ede6d6' },
  azulMarino: { label: 'Azul marino', value: '#1f2a44' },
  azulRey: { label: 'Azul rey', value: '#1f4fa3' },
  celeste: { label: 'Celeste', value: '#7fb3d5' },
  burdeo: { label: 'Burdeo', value: '#6d1a2c' },
  rojo: { label: 'Rojo', value: '#b3202a' },
  verdeBotella: { label: 'Verde botella', value: '#1e4d2b' },
  verde: { label: 'Verde', value: '#2e7d32' },
  morado: { label: 'Morado', value: '#5b2a86' },
  amarillo: { label: 'Amarillo', value: '#e3b505' },
  grisMelange: { label: 'Gris melange', value: '#9e9e9e' },
  grafito: { label: 'Gris grafito', value: '#4a4a4a' },
  cafe: { label: 'Café', value: '#8b5a2b' },
  kraft: { label: 'Kraft', value: '#c8a27a' },
  rosadoPalo: { label: 'Rosado palo', value: '#e8b4b8' },
  coral: { label: 'Coral', value: '#f28c6b' },
  menta: { label: 'Menta', value: '#7fd1c7' },
  lila: { label: 'Lila', value: '#d7b7e3' },
  dorado: { label: 'Dorado', value: '#c9a227' },
  plateado: { label: 'Plateado', value: '#c0c0c0' },
  bronce: { label: 'Bronce', value: '#a0663a' },
}

const logoOption = (label = 'Logo o escudo (PNG, JPG o PDF)'): SeedOption => ({
  type: 'FILE',
  label,
})

export const seedProducts: SeedProduct[] = [
  // ─── Graduaciones ────────────────────────────────────────────────
  {
    id: 'grad-stole-magna',
    name: 'Estola bordada Magna',
    description:
      'Estola de satín mate doble faz con escudo y año bordados en hilo metálico. Puntas en V con ribete.',
    category: 'graduaciones',
    price: 12990,
    images: img('grad-stole-magna', 2),
    tags: ['estolas', 'bordado', '4° medio', 'universidad'],
    specs: ['Satín mate doble faz', 'Bordado de hasta 8.000 puntadas', 'Largo 150 cm · ancho 12 cm'],
    personalization: 'Escudo, nombre de la generación y año bordados en ambas puntas.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 15 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Más vendido',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la estola',
        required: true,
        choices: [c.negro, c.azulMarino, c.burdeo, c.verdeBotella, c.dorado, c.blanco],
      },
      {
        type: 'COLOR',
        label: 'Color del bordado',
        required: true,
        choices: [c.dorado, c.plateado, c.blanco],
      },
      { type: 'TEXT', label: 'Texto a bordar (generación y año)' },
      logoOption('Escudo del colegio (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'grad-poleron-generacion',
    name: 'Polerón de generación',
    description:
      'Polerón canguro de algodón perchado con el nombre del curso al frente y los nombres de todos en la espalda.',
    category: 'graduaciones',
    price: 18990,
    images: img('grad-poleron-generacion', 2),
    tags: ['polerones', '4° medio', 'generación'],
    specs: ['Algodón perchado 320 g', 'Capucha con cordón y bolsillo canguro', 'Tallas XS a XXL'],
    personalization: 'Bordado frontal, nombres estampados en la espalda y apodo en la manga.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 18 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Top ventas',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color del polerón',
        required: true,
        choices: [c.negro, c.grisMelange, c.azulMarino, c.burdeo, c.blanco],
      },
      { type: 'TEXT', label: 'Nombre del curso o generación', required: true },
      logoOption('Diseño o lista de nombres (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'grad-birrete-signature',
    name: 'Birrete Signature',
    description:
      'Birrete de fieltro estructurado con tabla forrada en satín, banda elasticada y borla incluida.',
    category: 'graduaciones',
    price: 7990,
    images: img('grad-birrete-signature', 2),
    tags: ['birretes', 'graduación'],
    specs: ['Fieltro estructurado', 'Banda elasticada talla única', 'Borla de rayón incluida'],
    personalization: 'Color de borla institucional y botón forrado a tono.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Nuevo',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color del birrete',
        required: true,
        choices: [c.negro, c.azulMarino, c.burdeo, c.azulRey],
      },
      {
        type: 'COLOR',
        label: 'Color de la borla',
        required: true,
        choices: [c.dorado, c.blanco, c.rojo, c.celeste, c.verde],
      },
    ],
  },
  {
    id: 'grad-tunica-ceremonial',
    name: 'Túnica ceremonial premium',
    description:
      'Túnica de gabardina liviana con canesú, mangas campana y cierre invisible. Caída impecable en fotos.',
    category: 'graduaciones',
    price: 24990,
    images: img('grad-tunica-ceremonial', 2),
    tags: ['túnicas', 'confección', 'universidad'],
    specs: ['Gabardina liviana antiarrugas', 'Cierre invisible frontal', 'Tallas XS a XXL'],
    personalization: 'Vivos en color institucional y escudo bordado en el pecho.',
    minOrder: 'Mínimo 15 unidades',
    leadTime: 'Entrega en 20 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Premium',
    sampleEligible: false,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la túnica',
        required: true,
        choices: [c.negro, c.azulMarino, c.burdeo],
      },
      {
        type: 'COLOR',
        label: 'Color de los vivos',
        choices: [c.dorado, c.celeste, c.blanco, c.rojo],
      },
      logoOption('Escudo para bordar en el pecho (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'grad-tunica-escolar',
    name: 'Túnica escolar para licenciatura',
    description:
      'Túnica liviana para licenciaturas de 8° básico y 4° medio, confeccionada en el color de tu colegio.',
    category: 'graduaciones',
    price: 14990,
    images: img('grad-tunica-escolar', 2),
    tags: ['túnicas', 'colegios', 'licenciatura'],
    specs: ['Popelina liviana', 'Cierre frontal', 'Tallas 10 a XL'],
    personalization: 'Color institucional y estola a juego opcional.',
    minOrder: 'Mínimo 25 unidades',
    leadTime: 'Entrega en 15 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Ideal colegios',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la túnica',
        required: true,
        choices: [c.azulRey, c.azulMarino, c.negro, c.burdeo, c.verdeBotella],
      },
      { type: 'TEXT', label: 'Nombre del colegio' },
    ],
  },
  {
    id: 'grad-kit-kinder',
    name: 'Kit licenciatura kínder',
    description:
      'Túnica infantil, estola y birrete para la licenciatura de pre-kínder y kínder. Tela suave que no pica.',
    category: 'graduaciones',
    price: 12990,
    images: img('grad-kit-kinder', 2),
    tags: ['kínder', 'infantil', 'licenciatura'],
    specs: ['Tallas 2 a 8 años', 'Incluye túnica, estola y birrete', 'Tela suave y lavable'],
    personalization: 'Estola con nombre del jardín o colegio y año.',
    minOrder: 'Mínimo 15 kits',
    leadTime: 'Entrega en 12 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Favorito de apoderados',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la túnica',
        required: true,
        choices: [c.azulRey, c.morado, c.rojo, c.verde],
      },
      { type: 'TEXT', label: 'Nombre del jardín o colegio' },
    ],
  },
  {
    id: 'grad-stole-sublimada',
    name: 'Estola sublimada full color',
    description:
      'Estola de poliéster satinado impresa por sublimación: logos, degradados y fotos sin límite de colores.',
    category: 'graduaciones',
    price: 6990,
    images: img('grad-stole-sublimada', 2),
    tags: ['estolas', 'sublimación', 'económica'],
    specs: ['Poliéster satinado', 'Sublimación full color', 'Largo 140 cm · ancho 11 cm'],
    personalization: 'Diseño libre por ambas caras, sin costo extra por colores.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color base',
        choices: [c.blanco, c.azulRey, c.celeste, c.rojo, c.negro],
      },
      { type: 'TEXT', label: 'Nombre de la generación' },
      logoOption('Diseño o logo (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'grad-toga-muceta',
    name: 'Toga universitaria con muceta',
    description:
      'Toga de corte académico con muceta desmontable en el color de tu facultad. Ideal para titulaciones.',
    category: 'graduaciones',
    price: 34990,
    images: img('grad-toga-muceta', 2),
    tags: ['togas', 'universidad', 'titulación'],
    specs: ['Poliéster peso medio con caída', 'Muceta desmontable', 'Tallas S a XXL'],
    personalization: 'Muceta en color de facultad con ribete y escudo bordado.',
    minOrder: 'Mínimo 10 unidades',
    leadTime: 'Entrega en 20 días hábiles',
    availability: 'A_PEDIDO',
    badge: null,
    sampleEligible: false,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la muceta (facultad)',
        required: true,
        choices: [c.rojo, c.azulRey, c.verde, c.amarillo, c.morado, c.blanco],
      },
      { type: 'TEXT', label: 'Facultad o carrera' },
    ],
  },
  {
    id: 'grad-borla-anio',
    name: 'Borla con dije del año',
    description:
      'Borla de rayón con dije metálico del año de egreso. Se engancha en cualquier birrete y queda de recuerdo.',
    category: 'graduaciones',
    price: 3490,
    images: img('grad-borla-anio', 2),
    tags: ['borlas', 'accesorios', 'recuerdo'],
    specs: ['Rayón brillante 23 cm', 'Dije metálico dorado o plateado', 'Hasta 3 colores combinados'],
    personalization: 'Colores del colegio combinados y año de egreso.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 7 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Recuerdo',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color principal',
        required: true,
        choices: [c.blanco, c.rojo, c.azulMarino, c.celeste, c.dorado, c.verde],
      },
      {
        type: 'COLOR',
        label: 'Color secundario',
        choices: [c.blanco, c.rojo, c.azulMarino, c.celeste, c.dorado, c.verde],
      },
      { type: 'TEXT', label: 'Año del dije', required: true },
    ],
  },
  {
    id: 'grad-portadiploma',
    name: 'Porta diploma en cuerina',
    description:
      'Carpeta rígida forrada en cuerina con escudo estampado en caliente y cordón interior para sujetar el diploma.',
    category: 'graduaciones',
    price: 8990,
    images: img('grad-portadiploma', 1),
    tags: ['diplomas', 'ceremonia', 'recuerdo'],
    specs: ['Cuerina texturada', 'Formato carta u oficio', 'Estampado dorado o plateado'],
    personalization: 'Escudo y nombre de la institución estampados en la tapa.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 12 días hábiles',
    availability: 'A_PEDIDO',
    badge: null,
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la carpeta',
        required: true,
        choices: [c.burdeo, c.azulMarino, c.negro, c.verdeBotella],
      },
      {
        type: 'COLOR',
        label: 'Color del estampado',
        required: true,
        choices: [c.dorado, c.plateado],
      },
      logoOption('Escudo o logo (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'grad-medalla-honor',
    name: 'Medalla de honor con cinta',
    description:
      'Medalla metálica de 5 cm con relieve y cinta institucional. Para premiaciones y cuadro de honor.',
    category: 'graduaciones',
    price: 2990,
    images: img('grad-medalla-honor', 1),
    tags: ['medallas', 'premiación'],
    specs: ['Metal fundido con baño', 'Diámetro 5 cm', 'Cinta de 2,5 cm con cierre'],
    personalization: 'Escudo en relieve y texto de la distinción grabado al reverso.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: false,
    options: [
      {
        type: 'COLOR',
        label: 'Terminación',
        required: true,
        choices: [c.dorado, c.plateado, c.bronce],
      },
      {
        type: 'COLOR',
        label: 'Color de la cinta',
        choices: [c.rojo, c.azulMarino, c.celeste, c.verde],
      },
      { type: 'TEXT', label: 'Distinción (ej: Mejor compañero)' },
    ],
  },

  // ─── Artículos publicitarios ─────────────────────────────────────
  {
    id: 'mkt-kit-bienvenida',
    name: 'Kit de bienvenida ejecutivo',
    description:
      'Caja con libreta, bolígrafo metálico, botella térmica y tarjeta de bienvenida. Onboarding listo para entregar.',
    category: 'marketing',
    price: 24990,
    images: img('mkt-kit-bienvenida', 2),
    tags: ['welcome kit', 'onboarding', 'regalos'],
    specs: ['Caja rígida con cierre magnético', 'Libreta A5, bolígrafo y botella 500 ml', 'Tarjeta impresa'],
    personalization: 'Logo grabado en cada pieza, caja con logo y tarjeta con mensaje.',
    minOrder: 'Mínimo 25 kits',
    leadTime: 'Entrega en 12 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Personalizado',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la caja',
        required: true,
        choices: [c.negro, c.blanco, c.kraft],
      },
      { type: 'TEXT', label: 'Mensaje de la tarjeta' },
      logoOption('Logo de la empresa (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'mkt-polera-pique',
    name: 'Polera piqué corporativa',
    description:
      'Polera piqué con logo bordado en el pecho. Uniforme cómodo para equipos, ferias y terreno.',
    category: 'marketing',
    price: 9990,
    images: img('mkt-polera-pique', 3),
    tags: ['uniformes', 'textil', 'bordado'],
    specs: ['Piqué 220 g algodón/poliéster', 'Cuello y puños tejidos', 'Tallas S a XXXL'],
    personalization: 'Bordado de logo en pecho y manga.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 12 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Uniformes',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la polera',
        required: true,
        choices: [c.negro, c.blanco, c.azulMarino, c.grisMelange, c.rosadoPalo],
      },
      { type: 'TEXT', label: 'Detalle de tallas (ej: 5 S, 10 M, 5 L)' },
      logoOption(),
    ],
  },
  {
    id: 'mkt-botella-termica',
    name: 'Botella térmica de acero',
    description:
      'Botella de doble pared que mantiene el frío 24 horas y el calor 12 horas. Terminación mate.',
    category: 'marketing',
    price: 7990,
    images: img('mkt-botella-termica', 2),
    tags: ['botellas', 'eco', 'regalos'],
    specs: ['Acero inoxidable 304', '500 ml doble pared', 'Tapa hermética'],
    personalization: 'Grabado láser o impresión UV full color.',
    minOrder: 'Mínimo 25 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Top ventas',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color',
        required: true,
        choices: [c.blanco, c.negro, c.coral, c.menta, c.lila],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-textil-eco',
    name: 'Tote bag de algodón',
    description: 'Bolsa de algodón crudo con asas largas. La favorita para ferias, eventos y seminarios.',
    category: 'marketing',
    price: 3490,
    images: img('mkt-textil-eco', 3),
    tags: ['textil', 'eco', 'eventos'],
    specs: ['Algodón 140 g', '38 x 42 cm', 'Asas de 65 cm'],
    personalization: 'Serigrafía de 1 a 4 colores o bordado.',
    minOrder: 'Mínimo 50 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Top ventas',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la bolsa',
        required: true,
        choices: [c.crudo, c.blanco, c.negro],
      },
      logoOption('Logo o arte (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'mkt-kit-escritura',
    name: 'Kit de escritura premium',
    description:
      'Libreta con tapa de cuerina y bolígrafo metálico en estuche de regalo. Para directorios y clientes clave.',
    category: 'marketing',
    price: 12990,
    images: img('mkt-kit-escritura', 2),
    tags: ['escritura', 'ejecutivo', 'regalos'],
    specs: ['Libreta A5 de cuerina · 160 hojas', 'Bolígrafo metálico tinta azul', 'Estuche de regalo'],
    personalization: 'Grabado láser en el bolígrafo y bajo relieve en la libreta.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Nuevo',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la libreta',
        required: true,
        choices: [c.cafe, c.negro, c.azulMarino],
      },
      { type: 'TEXT', label: 'Texto a grabar en el bolígrafo' },
      logoOption(),
    ],
  },
  {
    id: 'mkt-jockey-bordado',
    name: 'Jockey bordado 6 paneles',
    description: 'Jockey de gabardina con cierre metálico regulable y logo bordado al frente.',
    category: 'marketing',
    price: 4990,
    images: img('mkt-jockey-bordado', 3),
    tags: ['jockeys', 'textil', 'bordado'],
    specs: ['Gabardina de algodón', '6 paneles con ojetillos', 'Cierre metálico regulable'],
    personalization: 'Bordado plano o 3D al frente y en el costado.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color del jockey',
        required: true,
        choices: [c.blanco, c.negro, c.grafito, c.amarillo, c.azulMarino],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-taza-sublimada',
    name: 'Taza cerámica sublimada',
    description: 'Taza blanca de 11 oz con impresión full color que resiste el lavavajillas.',
    category: 'marketing',
    price: 3490,
    images: img('mkt-taza-sublimada', 2),
    tags: ['tazas', 'oficina', 'sublimación'],
    specs: ['Cerámica 11 oz', 'Sublimación full color', 'Apta para lavavajillas'],
    personalization: 'Logo, frase o diseño envolvente de 360°.',
    minOrder: 'Mínimo 24 unidades',
    leadTime: 'Entrega en 7 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: true,
    options: [
      { type: 'TEXT', label: 'Frase o mensaje' },
      logoOption('Diseño o logo (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'mkt-libreta-a5',
    name: 'Libreta A5 tapa dura',
    description: 'Libreta con elástico, cinta marcadora y bolsillo interior. Tapa suave al tacto.',
    category: 'marketing',
    price: 4990,
    images: img('mkt-libreta-a5', 2),
    tags: ['libretas', 'oficina', 'escritura'],
    specs: ['A5 · 96 hojas lineadas', 'Tapa dura soft touch', 'Elástico y cinta marcadora'],
    personalization: 'Logo en bajo relieve o serigrafía en la tapa.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 10 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la tapa',
        required: true,
        choices: [c.azulRey, c.negro, c.rojo, c.grafito],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-mochila-ejecutiva',
    name: 'Mochila ejecutiva para notebook',
    description:
      'Mochila con compartimento acolchado para notebook de hasta 15,6" y bolsillo trasero antirrobo.',
    category: 'marketing',
    price: 21990,
    images: img('mkt-mochila-ejecutiva', 2),
    tags: ['mochilas', 'ejecutivo', 'regalos'],
    specs: ['Poliéster 600D repelente al agua', 'Compartimento notebook 15,6"', 'Bolsillo antirrobo'],
    personalization: 'Logo bordado o parche de goma.',
    minOrder: 'Mínimo 20 unidades',
    leadTime: 'Entrega en 15 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Premium',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de la mochila',
        required: true,
        choices: [c.negro, c.azulMarino, c.grafito],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-poleron-corporativo',
    name: 'Polerón corporativo bordado',
    description: 'Polerón canguro con capucha y logo bordado. Abrigado para equipos en terreno.',
    category: 'marketing',
    price: 19990,
    images: img('mkt-poleron-corporativo', 1),
    tags: ['polerones', 'uniformes', 'textil'],
    specs: ['Algodón perchado 300 g', 'Bolsillo canguro', 'Tallas S a XXL'],
    personalization: 'Bordado en pecho y espalda.',
    minOrder: 'Mínimo 15 unidades',
    leadTime: 'Entrega en 15 días hábiles',
    availability: 'A_PEDIDO',
    badge: null,
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color del polerón',
        required: true,
        choices: [c.grisMelange, c.negro, c.azulMarino, c.blanco],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-botella-aluminio',
    name: 'Botella deportiva de aluminio',
    description: 'Botella liviana con tapa y mosquetón. Perfecta para corridas, ferias y actividades outdoor.',
    category: 'marketing',
    price: 4490,
    images: img('mkt-botella-aluminio', 2),
    tags: ['botellas', 'deporte', 'eventos'],
    specs: ['Aluminio 600 ml', 'Tapa con mosquetón', 'Libre de BPA'],
    personalization: 'Tampografía de 1 color o grabado láser.',
    minOrder: 'Mínimo 50 unidades',
    leadTime: 'Entrega en 8 días hábiles',
    availability: 'DISPONIBLE',
    badge: null,
    sampleEligible: false,
    options: [
      {
        type: 'COLOR',
        label: 'Color',
        required: true,
        choices: [c.plateado, c.grafito, c.azulRey, c.rojo],
      },
      logoOption(),
    ],
  },
  {
    id: 'mkt-jockey-trucker',
    name: 'Gorro trucker con malla',
    description: 'Gorro trucker con frente de espuma y malla trasera. Ideal para activaciones de marca.',
    category: 'marketing',
    price: 3990,
    images: img('mkt-jockey-trucker', 2),
    tags: ['jockeys', 'activaciones', 'eventos'],
    specs: ['Frente de espuma', 'Malla transpirable', 'Broche regulable'],
    personalization: 'Sublimación full color al frente.',
    minOrder: 'Mínimo 50 unidades',
    leadTime: 'Entrega en 8 días hábiles',
    availability: 'DISPONIBLE',
    badge: 'Activaciones',
    sampleEligible: false,
    options: [
      {
        type: 'COLOR',
        label: 'Color de visera y malla',
        required: true,
        choices: [c.negro, c.blanco, c.azulMarino, c.rojo],
      },
      logoOption('Diseño (PNG, JPG o PDF)'),
    ],
  },
  {
    id: 'mkt-bolsa-yute',
    name: 'Bolsa de yute premium',
    description: 'Bolsa de yute laminado con asas acolchadas y base reforzada. Resistente y reutilizable.',
    category: 'marketing',
    price: 6990,
    images: img('mkt-bolsa-yute', 1),
    tags: ['bolsas', 'eco', 'regalos'],
    specs: ['Yute natural laminado', '42 x 33 x 18 cm', 'Asas acolchadas'],
    personalization: 'Logo o iniciales en serigrafía o transfer.',
    minOrder: 'Mínimo 30 unidades',
    leadTime: 'Entrega en 14 días hábiles',
    availability: 'A_PEDIDO',
    badge: 'Eco',
    sampleEligible: true,
    options: [
      {
        type: 'COLOR',
        label: 'Color de las asas',
        required: true,
        choices: [c.negro, c.azulMarino, c.kraft],
      },
      logoOption(),
    ],
  },
]
